"""Program entry for development and tests:  python server/app.py   (settings from SBO_CONFIG or config.json next to it).
The installed program uses server/sbo_main.py, which sets SBO_HOME to the ProgramData folder first."""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(HERE, 'core'))

import bootstrap  # noqa: E402
import httpd  # noqa: E402


def main(background=False):
    home = os.environ.get('SBO_HOME') or os.path.dirname(HERE)
    bootstrap.register_domains()
    try:
        from _assets import ASSETS  # generated by tools/make_assets.py for the installed program: the pages live inside SBO.exe
    except ImportError:
        ASSETS = None
    app = httpd.App(home, os.environ.get('SBO_CONFIG') or os.path.join(home, 'config.json'), root=os.path.dirname(HERE), assets=ASSETS)
    names = [n.strip() for n in os.environ.get('SBO_ENTITY_MODULES', '').split(',') if n.strip()]
    if not names:
        import business
        business.routes(app)
    for name in names:
        mod = __import__(name)
        if hasattr(mod, 'routes'):
            mod.routes(app)
    httpd.run(app, background)


if __name__ == '__main__':
    main('--background' in sys.argv)
