"""Builds web/js/ui/icons.js from the Lucide icon set (ISC licence, see web/lib/LICENSE-lucide.txt).

    npm pack lucide-static   (or download the tarball from the npm registry) and unpack it, then:
    python tools/make_icons.py <folder that contains the lucide "icons" directory>

Only the icons listed below are included, so the file stays small. Add a name here, rerun, commit the generated file.
"""
import os
import re
import sys

NAMES = '''house layout-dashboard users user building-2 briefcase kanban square-check-big calendar calendar-days file-text receipt wallet
banknote chart-column zap settings circle-help search plus x chevron-down chevron-right chevron-left menu sun moon globe keyboard bell
download upload trash-2 pencil funnel ellipsis phone mail message-circle map-pin tag clock triangle-alert check circle-check info star
target handshake list-checks inbox history paperclip link layers sparkles presentation laptop server monitor panel-left panel-right
log-out shield-check lock copy refresh-cw wifi-off arrow-right arrow-left grip-vertical eye file-spreadsheet folder timer user-plus
building circle-alert circle-x contact rotate-ccw save cloud cloud-off database lightbulb list undo-2 external-link palette type languages
notebook-pen layout-list circle-dot circle arrow-up arrow-down chevrons-up-down user-round hard-drive'''.split()


def main(src, out):
    icons = {}
    for n in NAMES:
        with open(os.path.join(src, 'icons', n + '.svg'), encoding='utf-8') as f:
            svg = f.read()
        inner = re.search(r'<svg[^>]*>(.*)</svg>', svg, re.S).group(1)
        icons[n] = ' '.join(inner.split())
    lines = ['// Generated by tools/make_icons.py from Lucide (ISC licence, see lib/LICENSE-lucide.txt). Do not edit.', 'export const ICONS = {']
    lines += [f'  {n!r}: {inner!r},' for n, inner in icons.items()]
    lines += ['};', '']
    with open(out, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    print(f'{len(icons)} icons written to {out}')


if __name__ == '__main__':
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    main(sys.argv[1], sys.argv[2] if len(sys.argv) > 2 else os.path.join(root, 'web', 'js', 'ui', 'icons.js'))
