"""Packs the web pages (everything under web/) into one Python module, so the installed program carries them inside
SBO.exe instead of as open files.

    python tools/make_assets.py [output file]      (default: server/_assets.py, which git ignores)

Keys are paths relative to web/ (index.html, css/..., js/..., lib/..., fonts/...), exactly what the server looks up.
"""
import os
import sys
import zlib

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WEB = os.path.join(ROOT, 'web')


def collect():
    files = {}
    for base, dirs, names in os.walk(WEB):
        dirs[:] = sorted(d for d in dirs if not d.startswith('.'))
        for n in sorted(names):
            if n.startswith('.'):
                continue
            p = os.path.join(base, n)
            files[os.path.relpath(p, WEB).replace(os.sep, '/')] = p
    return files


def main(out):
    files = collect()
    lines = ['"""Generated by tools/make_assets.py - the web pages of the program. Do not edit."""', 'import zlib', '', '_Z = {']
    for rel, path in sorted(files.items()):
        with open(path, 'rb') as f:
            lines.append(f'    {rel!r}: {zlib.compress(f.read(), 9)!r},')
    lines += ['}', 'ASSETS = {k: zlib.decompress(v) for k, v in _Z.items()}', 'del _Z', '']
    with open(out, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    print(f'{len(files)} files packed into {out}')


if __name__ == '__main__':
    main(sys.argv[1] if len(sys.argv) > 1 else os.path.join(ROOT, 'server', '_assets.py'))
